on: [push]


jobs:
  my-job:
    runs-on: ubuntu-lates

    steps:
    - uses: actions/checkout@v2
    - name: run the action
      id: hello
      uses: ./
      with:
        myInput: 'oriontaker'
    - name: output
      run: |
        echo ${{ steps.hello.outputs.memory}}
        echo "total memory successfully output"
